# Generated by Django 5.1.1 on 2024-10-05 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='header',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
